title: Guy King
author: Guy King
email: guy@zorncapital.com
description: > # this means to ignore newlines until "baseurl:"
  Web / backend development, devops.

github_username:  family-guy
facebook_username: dairy.myriad
headshot: /assets/images/headshot.jpeg

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
url: "https://guyrking.com"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
google_analytics: "UA-110244866-1"
disqus:
  shortname: homepage-5
