apiVersion: v1
kind: ConfigMap
metadata:
  name: https-redirect
data:
  redirect.conf: |
    server {
      listen 80;
      server_name guyrking.com;
      return 301 https://$host$request_uri;
    }
