apiVersion: v1
kind: Service
metadata:
  name: $CIRCLE_PROJECT_REPONAME-service
spec:  # defines behaviour of service
  selector:  # route service traffic to pod(s) with label keys and values matching this selector
    app: jekyll-nginx
  type:  NodePort
  ports:  # ports exposed by service
  - port: 8080  # exposed port
    targetPort: 443  # number or name of port to access on pod(s) targeted by service; matches `containerPort: 443` in deployment.yml; set to 443 because of https redirect
